### ISSUE TITLE
Blue courrier initialised

### ISSUE THREAD

**Issue by Jezo247** [bluedolmen/App-blue-courrier#1]
Hello JC,
Following on from https://redmine.bluedolmen.com/boards/4/topics/31?r=33
I now have a properly initialised BlueCourrier and now need to create the users and services;
Is that done under Blue courrier directly or do I need to create users under alf.../share?

**Comment by jckermagoret** [comment]
Hello Jezo,
you must create users in Alfresco Share > Admin tools (or through ldap synchronization).

Once created, you can put them in services with the role you want through yamma-admin > services.

JC

**Comment by Jezo247** [comment]
Hello JC, OK I'l add my users like that. Can you tell me at what point the syncronisation of users takes place IF my PC becomes member of a domain LDAP (windows server2012), or what action to take to synchronise with the AD?

**Comment by jckermagoret** [comment]
Hello,
It is an Alfresco feature. Go and have a look to the following:

* https://docs.alfresco.com/5.1/tasks/auth-example-oneldap-ad.html

HTH :-)

Jc

PS : I suggest you close this issue and open a new one. Wdyt ?

Envoyé de mon iPhone

Le 4 juin 2018 à 08:42, Jezo247 <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hello JC, OK I'l add my users like that. Can you tell me at what point the syncronisation of users takes place IF my PC becomes member of a domain LDAP (windows server2012), or what action to take to synchronise with the AD?

**Comment by Jezo247** [comment]
Hi JC, ok thanks that'll help me get started with users and groups now the intallation is complete and initialised.
I'll write up a very exact step-by-step from this thread so it can be used by a total noob to get going with bluecourrier;

**Comment by Jezo247** [comment]
Hello JC, thanks for that link, I'll study it carefully;
As promised, here's my detailed write-up documenting the installation, shared for the communities benefit.

https://docs.google.com/document/d/1wysyNGnUFTsPX6SJwyMQBF5hCKOKQwe0hZ15ot9Ctdw/edit?usp=sharing

**Comment by jckermagoret** [comment]
Hello,
thanks Jezo for your documentation. May you integrate it as a wiki page on the App-blue-courrier github?

Otherwise, are you using BlueCourrier for your needs, a customer?

Thanks again,

JC

**Comment by Jezo247** [comment]
Hello JC, I'll try to do as you ask and put it on the wiki.
Currently I'm still in testing phase to make sue Bluecourier will do what we want.
I'm going hrough the administrators manuel to correctly set up the services and users with privileges. 
Do you have links to videos that explain this process? As far as using Blue courrier itself are there any parts that require admin actions under alfesco share, or is it basically self-contained via yamma?

**Comment by Jezo247** [comment]
Update. I've done a completely new installation on another PC (Win7 64bit)  following this above procedure exactly and had the same error of initialisation. This was fixed using the Alfresco/share admin to create the bluecourrier site exactly as above and the rest of the admin initialisation under yamma-admin passed perfectly.
I'll close this now and create any future issues as a new one. Installation and initialisation is done.
:)
